// Code generated by svdxgen; DO NOT EDIT.

//go:build imxrt1060

// Package kpp provides access to the registers of the KPP peripheral.
//
// Instances:
//
//	KPP  KPP_BASE  -  KPP*  KPP Registers
//
// Registers:
//
//	0x000 16  KPCR  Keypad Control Register
//	0x002 16  KPSR  Keypad Status Register
//	0x004 16  KDDR  Keypad Data Direction Register
//	0x006 16  KPDR  Keypad Data Register
//
// Import:
//
//	github.com/embeddedgo/imxrt/p/mmap
package kpp

const (
	KRE        KPCR = 0xFF << 0 //+ Keypad Row Enable
	KRE_0      KPCR = 0x00 << 0 //  Row is not included in the keypad key press detect.
	KRE_1      KPCR = 0x01 << 0 //  Row is included in the keypad key press detect.
	KCO        KPCR = 0xFF << 8 //+ Keypad Column Strobe Open-Drain Enable
	TOTEM_POLE KPCR = 0x00 << 8 //  Column strobe output is totem pole drive.
	OPEN_DRAIN KPCR = 0x01 << 8 //  Column strobe output is open drain.
)

const (
	KREn = 0
	KCOn = 8
)

const (
	KPKD KPSR = 0x01 << 0 //+ Keypad Key Depress
	KPKR KPSR = 0x01 << 1 //+ Keypad Key Release
	KDSC KPSR = 0x01 << 2 //+ Key Depress Synchronizer Clear
	KRSS KPSR = 0x01 << 3 //+ Key Release Synchronizer Set
	KDIE KPSR = 0x01 << 8 //+ Keypad Key Depress Interrupt Enable
	KRIE KPSR = 0x01 << 9 //+ Keypad Release Interrupt Enable
)

const (
	KPKDn = 0
	KPKRn = 1
	KDSCn = 2
	KRSSn = 3
	KDIEn = 8
	KRIEn = 9
)

const (
	KRDD   KDDR = 0xFF << 0 //+ Keypad Row Data Direction
	INPUT  KDDR = 0x00 << 0 //  ROWn pin configured as an input.
	OUTPUT KDDR = 0x01 << 0 //  ROWn pin configured as an output.
	KCDD   KDDR = 0xFF << 8 //+ Keypad Column Data Direction Register
	INPUT  KDDR = 0x00 << 8 //  COLn pin is configured as an input.
	OUTPUT KDDR = 0x01 << 8 //  COLn pin is configured as an output.
)

const (
	KRDDn = 0
	KCDDn = 8
)

const (
	KRD KPDR = 0xFF << 0 //+ Keypad Row Data
	KCD KPDR = 0xFF << 8 //+ Keypad Column Data
)

const (
	KRDn = 0
	KCDn = 8
)
