// Code generated by svdxgen; DO NOT EDIT.

//go:build imxrt1060

// Package iomuxc_snvs_gpr provides access to the registers of the IOMUXC_SNVS_GPR peripheral.
//
// Instances:
//
//	IOMUXC_SNVS_GPR  IOMUXC_SNVS_GPR_BASE  -  -  IOMUXC
//
// Registers:
//
//	0x000 32  GPR0  GPR0 General Purpose Register
//	0x004 32  GPR1  GPR1 General Purpose Register
//	0x008 32  GPR2  GPR2 General Purpose Register
//	0x00C 32  GPR3  GPR3 General Purpose Register
//
// Import:
//
//	github.com/embeddedgo/imxrt/p/mmap
package iomuxc_snvs_gpr

const (
	LPSR_MODE_ENABLE     GPR3 = 0x01 << 0  //+ Set to enable LPSR mode.
	DCDC_STATUS_CAPT_CLR GPR3 = 0x01 << 1  //+ DCDC captured status clear
	POR_PULL_TYPE        GPR3 = 0x03 << 2  //+ POR_B pad control
	DCDC_IN_LOW_VOL      GPR3 = 0x01 << 16 //+ DCDC_IN low voltage detect.
	DCDC_OVER_CUR        GPR3 = 0x01 << 17 //+ DCDC output over current alert
	DCDC_OVER_VOL        GPR3 = 0x01 << 18 //+ DCDC output over voltage alert
	DCDC_STS_DC_OK       GPR3 = 0x01 << 19 //+ DCDC status OK
)

const (
	LPSR_MODE_ENABLEn     = 0
	DCDC_STATUS_CAPT_CLRn = 1
	POR_PULL_TYPEn        = 2
	DCDC_IN_LOW_VOLn      = 16
	DCDC_OVER_CURn        = 17
	DCDC_OVER_VOLn        = 18
	DCDC_STS_DC_OKn       = 19
)
