// DO NOT EDIT THIS FILE. GENERATED BY svdxgen.

//go:build imxrt1060

// Package wdog provides access to the registers of the WDOG peripheral.
//
// Instances:
//
//	WDOG1  WDOG1_BASE  -  WDOG1*
//	WDOG2  WDOG2_BASE  -  WDOG2*
//
// Registers:
//
//	0x000 16  WCR   Watchdog Control Register
//	0x002 16  WSR   Watchdog Service Register
//	0x004 16  WRSR  Watchdog Reset Status Register
//	0x006 16  WICR  Watchdog Interrupt Control Register
//	0x008 16  WMCR  Watchdog Miscellaneous Control Register
//
// Import:
//
//	github.com/embeddedgo/imxrt/p/mmap
package wdog

const (
	WDZST  WCR = 0x01 << 0 //+ WDZST
	WDBG   WCR = 0x01 << 1 //+ WDBG
	WDE    WCR = 0x01 << 2 //+ WDE
	WDT    WCR = 0x01 << 3 //+ WDT
	SRS    WCR = 0x01 << 4 //+ SRS
	WDA    WCR = 0x01 << 5 //+ WDA
	SRE    WCR = 0x01 << 6 //+ software reset extension, an option way to generate software reset
	WDW    WCR = 0x01 << 7 //+ WDW
	WT     WCR = 0xFF << 8 //+ WT
	WT_0   WCR = 0x00 << 8 //  - 0.5 Seconds (Default).
	WT_1   WCR = 0x01 << 8 //  - 1.0 Seconds.
	WT_2   WCR = 0x02 << 8 //  - 1.5 Seconds.
	WT_3   WCR = 0x03 << 8 //  - 2.0 Seconds.
	WT_255 WCR = 0xFF << 8 //  - 128 Seconds.
)

const (
	WDZSTn = 0
	WDBGn  = 1
	WDEn   = 2
	WDTn   = 3
	SRSn   = 4
	WDAn   = 5
	SREn   = 6
	WDWn   = 7
	WTn    = 8
)

const (
	SFTW WRSR = 0x01 << 0 //+ SFTW
	TOUT WRSR = 0x01 << 1 //+ TOUT
	POR  WRSR = 0x01 << 4 //+ POR
)

const (
	SFTWn = 0
	TOUTn = 1
	PORn  = 4
)

const (
	WICT     WICR = 0xFF << 0  //+ WICT
	WICT_0   WICR = 0x00 << 0  //  WICT[7:0] = Time duration between interrupt and time-out is 0 seconds.
	WICT_1   WICR = 0x01 << 0  //  WICT[7:0] = Time duration between interrupt and time-out is 0.5 seconds.
	WICT_4   WICR = 0x04 << 0  //  WICT[7:0] = Time duration between interrupt and time-out is 2 seconds (Default).
	WICT_255 WICR = 0xFF << 0  //  WICT[7:0] = Time duration between interrupt and time-out is 127.5 seconds.
	WTIS     WICR = 0x01 << 14 //+ WTIS
	WIE      WICR = 0x01 << 15 //+ WIE
)

const (
	WICTn = 0
	WTISn = 14
	WIEn  = 15
)

const (
	PDE WMCR = 0x01 << 0 //+ PDE
)

const (
	PDEn = 0
)
