// DO NOT EDIT THIS FILE. GENERATED BY svdxgen.

//go:build imxrt1060

// Package dmamux provides access to the registers of the DMAMUX peripheral.
//
// Instances:
//
//	DMAMUX  DMAMUX_BASE  -  -  DMA_CH_MUX
//
// Registers:
//
//	0x000 32  CHCFG[32]  Channel 0 Configuration Register
//
// Import:
//
//	github.com/embeddedgo/imxrt/p/mmap
package dmamux

const (
	SOURCE CHCFG = 0x7F << 0  //+ DMA Channel Source (Slot Number)
	A_ON   CHCFG = 0x01 << 29 //+ DMA Channel Always Enable
	TRIG   CHCFG = 0x01 << 30 //+ DMA Channel Trigger Enable
	ENBL   CHCFG = 0x01 << 31 //+ DMA Mux Channel Enable
)

const (
	SOURCEn = 0
	A_ONn   = 29
	TRIGn   = 30
	ENBLn   = 31
)
