// DO NOT EDIT THIS FILE. GENERATED BY svdxgen.

//go:build imxrt1060

// Package flexram provides access to the registers of the FLEXRAM peripheral.
//
// Instances:
//  FLEXRAM  FLEXRAM_BASE  -  FLEXRAM*
// Registers:
//  0x000 32  TCM_CTRL     TCM CRTL Register
//  0x010 32  INT_STATUS   Interrupt Status Register
//  0x014 32  INT_STAT_EN  Interrupt Status Enable Register
//  0x018 32  INT_SIG_EN   Interrupt Enable Register
// Import:
//  github.com/embeddedgo/imxrt/p/mmap
package flexram

const (
	TCM_WWAIT_EN   TCM_CTRL = 0x01 << 0 //+ TCM Write Wait Mode Enable
	TCM_WWAIT_EN_0 TCM_CTRL = 0x00 << 0 //  TCM write fast mode: Write RAM accesses are expected to be finished in 1-cycle.
	TCM_WWAIT_EN_1 TCM_CTRL = 0x01 << 0 //  TCM write wait mode: Write RAM accesses are expected to be finished in 2-cycles.
	TCM_RWAIT_EN   TCM_CTRL = 0x01 << 1 //+ TCM Read Wait Mode Enable
	TCM_RWAIT_EN_0 TCM_CTRL = 0x00 << 1 //  TCM read fast mode: Read RAM accesses are expected to be finished in 1-cycle.
	TCM_RWAIT_EN_1 TCM_CTRL = 0x01 << 1 //  TCM read wait mode: Read RAM accesses are expected to be finished in 2-cycles.
	FORCE_CLK_ON   TCM_CTRL = 0x01 << 2 //+ Force RAM Clock Always On
)

const (
	TCM_WWAIT_ENn = 0
	TCM_RWAIT_ENn = 1
	FORCE_CLK_ONn = 2
)

const (
	ITCM_ERR_STATUS    INT_STATUS = 0x01 << 3 //+ ITCM Access Error Status
	ITCM_ERR_STATUS_0  INT_STATUS = 0x00 << 3 //  ITCM access error does not happen
	ITCM_ERR_STATUS_1  INT_STATUS = 0x01 << 3 //  ITCM access error happens.
	DTCM_ERR_STATUS    INT_STATUS = 0x01 << 4 //+ DTCM Access Error Status
	DTCM_ERR_STATUS_0  INT_STATUS = 0x00 << 4 //  DTCM access error does not happen
	DTCM_ERR_STATUS_1  INT_STATUS = 0x01 << 4 //  DTCM access error happens.
	OCRAM_ERR_STATUS   INT_STATUS = 0x01 << 5 //+ OCRAM Access Error Status
	OCRAM_ERR_STATUS_0 INT_STATUS = 0x00 << 5 //  OCRAM access error does not happen
	OCRAM_ERR_STATUS_1 INT_STATUS = 0x01 << 5 //  OCRAM access error happens.
)

const (
	ITCM_ERR_STATUSn  = 3
	DTCM_ERR_STATUSn  = 4
	OCRAM_ERR_STATUSn = 5
)

const (
	ITCM_ERR_STAT_EN    INT_STAT_EN = 0x01 << 3 //+ ITCM Access Error Status Enable
	ITCM_ERR_STAT_EN_0  INT_STAT_EN = 0x00 << 3 //  Masked
	ITCM_ERR_STAT_EN_1  INT_STAT_EN = 0x01 << 3 //  Enabled
	DTCM_ERR_STAT_EN    INT_STAT_EN = 0x01 << 4 //+ DTCM Access Error Status Enable
	DTCM_ERR_STAT_EN_0  INT_STAT_EN = 0x00 << 4 //  Masked
	DTCM_ERR_STAT_EN_1  INT_STAT_EN = 0x01 << 4 //  Enabled
	OCRAM_ERR_STAT_EN   INT_STAT_EN = 0x01 << 5 //+ OCRAM Access Error Status Enable
	OCRAM_ERR_STAT_EN_0 INT_STAT_EN = 0x00 << 5 //  Masked
	OCRAM_ERR_STAT_EN_1 INT_STAT_EN = 0x01 << 5 //  Enabled
)

const (
	ITCM_ERR_STAT_ENn  = 3
	DTCM_ERR_STAT_ENn  = 4
	OCRAM_ERR_STAT_ENn = 5
)

const (
	ITCM_ERR_SIG_EN    INT_SIG_EN = 0x01 << 3 //+ ITCM Access Error Interrupt Enable
	ITCM_ERR_SIG_EN_0  INT_SIG_EN = 0x00 << 3 //  Masked
	ITCM_ERR_SIG_EN_1  INT_SIG_EN = 0x01 << 3 //  Enabled
	DTCM_ERR_SIG_EN    INT_SIG_EN = 0x01 << 4 //+ DTCM Access Error Interrupt Enable
	DTCM_ERR_SIG_EN_0  INT_SIG_EN = 0x00 << 4 //  Masked
	DTCM_ERR_SIG_EN_1  INT_SIG_EN = 0x01 << 4 //  Enabled
	OCRAM_ERR_SIG_EN   INT_SIG_EN = 0x01 << 5 //+ OCRAM Access Error Interrupt Enable
	OCRAM_ERR_SIG_EN_0 INT_SIG_EN = 0x00 << 5 //  Masked
	OCRAM_ERR_SIG_EN_1 INT_SIG_EN = 0x01 << 5 //  Enabled
)

const (
	ITCM_ERR_SIG_ENn  = 3
	DTCM_ERR_SIG_ENn  = 4
	OCRAM_ERR_SIG_ENn = 5
)
