// Copyright 2022 The Embedded Go Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package iomux

import (
	"embedded/mmio"
	"unsafe"

	"github.com/embeddedgo/imxrt/p/mmap"
)

type Daisy_ struct {
	ANATOP_USB_OTG1_ID          mmio.U32
	ANATOP_USB_OTG2_ID          mmio.U32
	CCM_PMIC_READY              mmio.U32
	CSI_DATA02                  mmio.U32
	CSI_DATA03                  mmio.U32
	CSI_DATA04                  mmio.U32
	CSI_DATA05                  mmio.U32
	CSI_DATA06                  mmio.U32
	CSI_DATA07                  mmio.U32
	CSI_DATA08                  mmio.U32
	CSI_DATA09                  mmio.U32
	CSI_HSYNC                   mmio.U32
	CSI_PIXCLK                  mmio.U32
	CSI_VSYNC                   mmio.U32
	ENET_IPG_CLK_RMII           mmio.U32
	ENET_MDIO                   mmio.U32
	ENET0_RXDATA                mmio.U32
	ENET1_RXDATA                mmio.U32
	ENET_RXEN                   mmio.U32
	ENET_RXERR                  mmio.U32
	ENET0_TIMER                 mmio.U32
	ENET_TXCLK                  mmio.U32
	FLEXCAN1_RX                 mmio.U32
	FLEXCAN2_RX                 mmio.U32
	FLEXPWM1_PWMA3              mmio.U32
	FLEXPWM1_PWMA0              mmio.U32
	FLEXPWM1_PWMA1              mmio.U32
	FLEXPWM1_PWMA2              mmio.U32
	FLEXPWM1_PWMB3              mmio.U32
	FLEXPWM1_PWMB0              mmio.U32
	FLEXPWM1_PWMB1              mmio.U32
	FLEXPWM1_PWMB2              mmio.U32
	FLEXPWM2_PWMA3              mmio.U32
	FLEXPWM2_PWMA0              mmio.U32
	FLEXPWM2_PWMA1              mmio.U32
	FLEXPWM2_PWMA2              mmio.U32
	FLEXPWM2_PWMB3              mmio.U32
	FLEXPWM2_PWMB0              mmio.U32
	FLEXPWM2_PWMB1              mmio.U32
	FLEXPWM2_PWMB2              mmio.U32
	FLEXPWM4_PWMA0              mmio.U32
	FLEXPWM4_PWMA1              mmio.U32
	FLEXPWM4_PWMA2              mmio.U32
	FLEXPWM4_PWMA3              mmio.U32
	FLEXSPIA_DQS                mmio.U32
	FLEXSPIA_DATA0              mmio.U32
	FLEXSPIA_DATA1              mmio.U32
	FLEXSPIA_DATA2              mmio.U32
	FLEXSPIA_DATA3              mmio.U32
	FLEXSPIB_DATA0              mmio.U32
	FLEXSPIB_DATA1              mmio.U32
	FLEXSPIB_DATA2              mmio.U32
	FLEXSPIB_DATA3              mmio.U32
	FLEXSPIA_SCK                mmio.U32
	LPI2C1_SCL                  mmio.U32
	LPI2C1_SDA                  mmio.U32
	LPI2C2_SCL                  mmio.U32
	LPI2C2_SDA                  mmio.U32
	LPI2C3_SCL                  mmio.U32
	LPI2C3_SDA                  mmio.U32
	LPI2C4_SCL                  mmio.U32
	LPI2C4_SDA                  mmio.U32
	LPSPI1_PCS0                 mmio.U32
	LPSPI1_SCK                  mmio.U32
	LPSPI1_SDI                  mmio.U32
	LPSPI1_SDO                  mmio.U32
	LPSPI2_PCS0                 mmio.U32
	LPSPI2_SCK                  mmio.U32
	LPSPI2_SDI                  mmio.U32
	LPSPI2_SDO                  mmio.U32
	LPSPI3_PCS0                 mmio.U32
	LPSPI3_SCK                  mmio.U32
	LPSPI3_SDI                  mmio.U32
	LPSPI3_SDO                  mmio.U32
	LPSPI4_PCS0                 mmio.U32
	LPSPI4_SCK                  mmio.U32
	LPSPI4_SDI                  mmio.U32
	LPSPI4_SDO                  mmio.U32
	LPUART2_RX                  mmio.U32
	LPUART2_TX                  mmio.U32
	LPUART3_CTS_B               mmio.U32
	LPUART3_RX                  mmio.U32
	LPUART3_TX                  mmio.U32
	LPUART4_RX                  mmio.U32
	LPUART4_TX                  mmio.U32
	LPUART5_RX                  mmio.U32
	LPUART5_TX                  mmio.U32
	LPUART6_RX                  mmio.U32
	LPUART6_TX                  mmio.U32
	LPUART7_RX                  mmio.U32
	LPUART7_TX                  mmio.U32
	LPUART8_RX                  mmio.U32
	LPUART8_TX                  mmio.U32
	NMI                         mmio.U32
	QTIMER2_TIMER0              mmio.U32
	QTIMER2_TIMER1              mmio.U32
	QTIMER2_TIMER2              mmio.U32
	QTIMER2_TIMER3              mmio.U32
	QTIMER3_TIMER0              mmio.U32
	QTIMER3_TIMER1              mmio.U32
	QTIMER3_TIMER2              mmio.U32
	QTIMER3_TIMER3              mmio.U32
	SAI1_MCLK2                  mmio.U32
	SAI1_RX_BCLK                mmio.U32
	SAI1_RX_DATA0               mmio.U32
	SAI1_RX_DATA1               mmio.U32
	SAI1_RX_DATA2               mmio.U32
	SAI1_RX_DATA3               mmio.U32
	SAI1_RX_SYNC                mmio.U32
	SAI1_TX_BCLK                mmio.U32
	SAI1_TX_SYNC                mmio.U32
	SAI2_MCLK2                  mmio.U32
	SAI2_RX_BCLK                mmio.U32
	SAI2_RX_DATA0               mmio.U32
	SAI2_RX_SYNC                mmio.U32
	SAI2_TX_BCLK                mmio.U32
	SAI2_TX_SYNC                mmio.U32
	SPDIF_IN                    mmio.U32
	USB_OTG2_OC                 mmio.U32
	USB_OTG1_OC                 mmio.U32
	USDHC1_CD_B                 mmio.U32
	USDHC1_WP                   mmio.U32
	USDHC2_CLK                  mmio.U32
	USDHC2_CD_B                 mmio.U32
	USDHC2_CMD                  mmio.U32
	USDHC2_DATA0                mmio.U32
	USDHC2_DATA1                mmio.U32
	USDHC2_DATA2                mmio.U32
	USDHC2_DATA3                mmio.U32
	USDHC2_DATA4                mmio.U32
	USDHC2_DATA5                mmio.U32
	USDHC2_DATA6                mmio.U32
	USDHC2_DATA7                mmio.U32
	USDHC2_WP                   mmio.U32
	XBAR1_IN02                  mmio.U32
	XBAR1_IN03                  mmio.U32
	XBAR1_IN04                  mmio.U32
	XBAR1_IN05                  mmio.U32
	XBAR1_IN06                  mmio.U32
	XBAR1_IN07                  mmio.U32
	XBAR1_IN08                  mmio.U32
	XBAR1_IN09                  mmio.U32
	XBAR1_IN17                  mmio.U32
	XBAR1_IN18                  mmio.U32
	XBAR1_IN20                  mmio.U32
	XBAR1_IN22                  mmio.U32
	XBAR1_IN23                  mmio.U32
	XBAR1_IN24                  mmio.U32
	XBAR1_IN14                  mmio.U32
	XBAR1_IN15                  mmio.U32
	XBAR1_IN16                  mmio.U32
	XBAR1_IN25                  mmio.U32
	XBAR1_IN19                  mmio.U32
	XBAR1_IN21                  mmio.U32
	_                           [44]uint32
	ENET2_IPG_CLK_RMII          mmio.U32
	ENET2_IPP_IND_MAC0_MDIO     mmio.U32
	ENET2_IPP_IND_MAC0_RXDATA_0 mmio.U32
	ENET2_IPP_IND_MAC0_RXDATA_1 mmio.U32
	ENET2_IPP_IND_MAC0_RXEN     mmio.U32
	ENET2_IPP_IND_MAC0_RXERR    mmio.U32
	ENET2_IPP_IND_MAC0_TIMER_0  mmio.U32
	ENET2_IPP_IND_MAC0_TXCLK    mmio.U32
	FLEXSPI2_IPP_IND_DQS_FA     mmio.U32
	FLEXSPI2_IPP_IND_IO_FA_BIT0 mmio.U32
	FLEXSPI2_IPP_IND_IO_FA_BIT1 mmio.U32
	FLEXSPI2_IPP_IND_IO_FA_BIT2 mmio.U32
	FLEXSPI2_IPP_IND_IO_FA_BIT3 mmio.U32
	FLEXSPI2_IPP_IND_IO_FB_BIT0 mmio.U32
	FLEXSPI2_IPP_IND_IO_FB_BIT1 mmio.U32
	FLEXSPI2_IPP_IND_IO_FB_BIT2 mmio.U32
	FLEXSPI2_IPP_IND_IO_FB_BIT3 mmio.U32
	FLEXSPI2_IPP_IND_SCK_FA     mmio.U32
	FLEXSPI2_IPP_IND_SCK_FB     mmio.U32
	GPT1_IPP_IND_CAPIN1         mmio.U32
	GPT1_IPP_IND_CAPIN2         mmio.U32
	GPT1_IPP_IND_CLKIN          mmio.U32
	GPT2_IPP_IND_CAPIN1         mmio.U32
	GPT2_IPP_IND_CAPIN2         mmio.U32
	GPT2_IPP_IND_CLKIN          mmio.U32
	SAI3_IPG_CLK_SAI_MCLK_2     mmio.U32
	SAI3_IPP_IND_SAI_RXBCLK     mmio.U32
	SAI3_IPP_IND_SAI_RXDATA_0   mmio.U32
	SAI3_IPP_IND_SAI_RXSYNC     mmio.U32
	SAI3_IPP_IND_SAI_TXBCLK     mmio.U32
	SAI3_IPP_IND_SAI_TXSYNC     mmio.U32
	SEMC_I_IPP_IND_DQS4         mmio.U32
	CANFD_IPP_IND_CANRX         mmio.U32
}

func Daisy() *Daisy_ { return (*Daisy_)(unsafe.Pointer(mmap.IOMUXC_BASE + (5+248)*4)) }
