// DO NOT EDIT THIS FILE. GENERATED BY svdxgen.

//go:build imxrt1060

// Package mmap provides base memory adresses for all peripherals.
package mmap

// ACMP
const (
	CMP1_BASE uintptr = 0x40094000 // High-Speed Comparator (CMP), Voltage Reference (VREF) Digital-to-Analog Converter (DAC), and Analog Mux (ANMUX)
	CMP2_BASE uintptr = 0x40094008 // High-Speed Comparator (CMP), Voltage Reference (VREF) Digital-to-Analog Converter (DAC), and Analog Mux (ANMUX)
	CMP3_BASE uintptr = 0x40094010 // High-Speed Comparator (CMP), Voltage Reference (VREF) Digital-to-Analog Converter (DAC), and Analog Mux (ANMUX)
	CMP4_BASE uintptr = 0x40094018 // High-Speed Comparator (CMP), Voltage Reference (VREF) Digital-to-Analog Converter (DAC), and Analog Mux (ANMUX)
)

// ADC
const (
	ADC1_BASE uintptr = 0x400C4000 // Analog-to-Digital Converter
	ADC2_BASE uintptr = 0x400C8000 // Analog-to-Digital Converter
)

// ADC_ETC
const (
	ADC_ETC_BASE uintptr = 0x403B0000 // ADC_ETC
)

// AIPSTZ
const (
	AIPSTZ1_BASE uintptr = 0x4007C000 // AIPSTZ Control Registers
	AIPSTZ2_BASE uintptr = 0x4017C000 // AIPSTZ Control Registers
	AIPSTZ3_BASE uintptr = 0x4027C000 // AIPSTZ Control Registers
	AIPSTZ4_BASE uintptr = 0x4037C000 // AIPSTZ Control Registers
)

// AOI
const (
	AOI1_BASE uintptr = 0x403B4000 // AND/OR/INVERT module
	AOI2_BASE uintptr = 0x403B8000 // AND/OR/INVERT module
)

// BEE
const (
	BEE_BASE uintptr = 0x403EC000 // Bus Encryption Engine
)

// CAN
const (
	CAN1_BASE uintptr = 0x401D0000 // FLEXCAN
	CAN2_BASE uintptr = 0x401D4000 // FLEXCAN
	CAN3_BASE uintptr = 0x401D8000 // CAN
)

// CCM
const (
	CCM_BASE uintptr = 0x400FC000 // CCM
)

// CCM_ANALOG
const (
	CCM_ANALOG_BASE uintptr = 0x400D8000 // CCM_ANALOG
)

// CSI
const (
	CSI_BASE uintptr = 0x402BC000 // CSI
)

// CSU
const (
	CSU_BASE uintptr = 0x400DC000 // CSU registers
)

// DCDC
const (
	DCDC_BASE uintptr = 0x40080000 // DCDC
)

// DCP
const (
	DCP_BASE uintptr = 0x402FC000 // DCP register reference index
)

// DMA
const (
	DMA0_BASE uintptr = 0x400E8000 // DMA
)

// DMAMUX
const (
	DMAMUX_BASE uintptr = 0x400EC000 // DMA_CH_MUX
)

// ENC
const (
	ENC1_BASE uintptr = 0x403C8000 // Quadrature Decoder
	ENC2_BASE uintptr = 0x403CC000 // Quadrature Decoder
	ENC3_BASE uintptr = 0x403D0000 // Quadrature Decoder
	ENC4_BASE uintptr = 0x403D4000 // Quadrature Decoder
)

// ENET
const (
	ENET_BASE  uintptr = 0x402D8000 // Ethernet MAC-NET Core
	ENET2_BASE uintptr = 0x402D4000 // Ethernet MAC-NET Core
)

// EWM
const (
	EWM_BASE uintptr = 0x400B4000 // EWM
)

// FLEXIO
const (
	FLEXIO1_BASE uintptr = 0x401AC000 // FLEXIO
	FLEXIO2_BASE uintptr = 0x401B0000 // FLEXIO
	FLEXIO3_BASE uintptr = 0x42020000 // FLEXIO
)

// FLEXRAM
const (
	FLEXRAM_BASE uintptr = 0x400B0000 // FLEXRAM
)

// FlexSPI
const (
	FLEXSPI_BASE  uintptr = 0x402A8000 // FlexSPI
	FLEXSPI2_BASE uintptr = 0x402A4000 // FlexSPI
)

// GPC
const (
	GPC_BASE uintptr = 0x400F4000 // GPC
)

// GPIO
const (
	GPIO1_BASE uintptr = 0x401B8000 // GPIO
	GPIO2_BASE uintptr = 0x401BC000 // GPIO
	GPIO3_BASE uintptr = 0x401C0000 // GPIO
	GPIO4_BASE uintptr = 0x401C4000 // GPIO
	GPIO5_BASE uintptr = 0x400C0000 // GPIO
	GPIO6_BASE uintptr = 0x42000000 // GPIO
	GPIO7_BASE uintptr = 0x42004000 // GPIO
	GPIO8_BASE uintptr = 0x42008000 // GPIO
	GPIO9_BASE uintptr = 0x4200C000 // GPIO
)

// GPT
const (
	GPT1_BASE uintptr = 0x401EC000 // GPT
	GPT2_BASE uintptr = 0x401F0000 // GPT
)

// I2S
const (
	SAI1_BASE uintptr = 0x40384000 // I2S
	SAI2_BASE uintptr = 0x40388000 // I2S
	SAI3_BASE uintptr = 0x4038C000 // I2S
)

// IOMUXC
const (
	IOMUXC_BASE uintptr = 0x401F8000 // IOMUXC
)

// IOMUXC_GPR
const (
	IOMUXC_GPR_BASE uintptr = 0x400AC000 // IOMUXC_GPR
)

// IOMUXC_SNVS
const (
	IOMUXC_SNVS_BASE uintptr = 0x400A8000 // IOMUXC_SNVS
)

// IOMUXC_SNVS_GPR
const (
	IOMUXC_SNVS_GPR_BASE uintptr = 0x400A4000 // IOMUXC
)

// KPP
const (
	KPP_BASE uintptr = 0x401FC000 // KPP Registers
)

// LCDIF
const (
	LCDIF_BASE uintptr = 0x402B8000 // LCDIF Register Reference Index
)

// LPI2C
const (
	LPI2C1_BASE uintptr = 0x403F0000 // LPI2C
	LPI2C2_BASE uintptr = 0x403F4000 // LPI2C
	LPI2C3_BASE uintptr = 0x403F8000 // LPI2C
	LPI2C4_BASE uintptr = 0x403FC000 // LPI2C
)

// LPSPI
const (
	LPSPI1_BASE uintptr = 0x40394000 // LPSPI
	LPSPI2_BASE uintptr = 0x40398000 // LPSPI
	LPSPI3_BASE uintptr = 0x4039C000 // LPSPI
	LPSPI4_BASE uintptr = 0x403A0000 // LPSPI
)

// LPUART
const (
	LPUART1_BASE uintptr = 0x40184000 // LPUART
	LPUART2_BASE uintptr = 0x40188000 // LPUART
	LPUART3_BASE uintptr = 0x4018C000 // LPUART
	LPUART4_BASE uintptr = 0x40190000 // LPUART
	LPUART5_BASE uintptr = 0x40194000 // LPUART
	LPUART6_BASE uintptr = 0x40198000 // LPUART
	LPUART7_BASE uintptr = 0x4019C000 // LPUART
	LPUART8_BASE uintptr = 0x401A0000 // LPUART
)

// NVIC
const (
	NVIC_BASE uintptr = 0xE000E100 // Nested Vectored Interrupt Controller
)

// OCOTP
const (
	OCOTP_BASE uintptr = 0x401F4000 // OCOTP
)

// PGC
const (
	PGC_BASE uintptr = 0x400F4000 // PGC
)

// PIT
const (
	PIT_BASE uintptr = 0x40084000 // PIT
)

// PMU
const (
	PMU_BASE uintptr = 0x400D8000 // PMU
)

// PWM
const (
	PWM1_BASE uintptr = 0x403DC000 // PWM
	PWM2_BASE uintptr = 0x403E0000 // PWM
	PWM3_BASE uintptr = 0x403E4000 // PWM
	PWM4_BASE uintptr = 0x403E8000 // PWM
)

// PXP
const (
	PXP_BASE uintptr = 0x402B4000 // PXP v2.0 Register Reference Index
)

// ROMC
const (
	ROMC_BASE uintptr = 0x40180000 // ROMC
)

// RTWDOG
const (
	RTWDOG_BASE uintptr = 0x400BC000 // WDOG
)

// SCB
const (
	SystemControl_BASE uintptr = 0xE000E000 // System Control Block
)

// SEMC
const (
	SEMC_BASE uintptr = 0x402F0000 // SEMC
)

// SNVS
const (
	SNVS_BASE uintptr = 0x400D4000 // SNVS
)

// SPDIF
const (
	SPDIF_BASE uintptr = 0x40380000 // SPDIF
)

// SRC
const (
	SRC_BASE uintptr = 0x400F8000 // SRC
)

// TEMPMON
const (
	TEMPMON_BASE uintptr = 0x400D8000 // Temperature Monitor
)

// TMR
const (
	TMR1_BASE uintptr = 0x401DC000 // Quad Timer
	TMR2_BASE uintptr = 0x401E0000 // Quad Timer
	TMR3_BASE uintptr = 0x401E4000 // Quad Timer
	TMR4_BASE uintptr = 0x401E8000 // Quad Timer
)

// TRNG
const (
	TRNG_BASE uintptr = 0x400CC000 // TRNG
)

// TSC
const (
	TSC_BASE uintptr = 0x400E0000 // Touch Screen Controller
)

// USB
const (
	USB1_BASE uintptr = 0x402E0000 // USB
	USB2_BASE uintptr = 0x402E0200 // USB
)

// USBNC
const (
	USBNC1_BASE uintptr = 0x402E0000 // USB
	USBNC2_BASE uintptr = 0x402E0004 // USB
)

// USBPHY
const (
	USBPHY1_BASE uintptr = 0x400D9000 // USBPHY Register Reference Index
	USBPHY2_BASE uintptr = 0x400DA000 // USBPHY Register Reference Index
)

// USB_ANALOG
const (
	USB_ANALOG_BASE uintptr = 0x400D8000 // USB Analog
)

// USDHC
const (
	USDHC1_BASE uintptr = 0x402C0000 // uSDHC
	USDHC2_BASE uintptr = 0x402C4000 // uSDHC
)

// WDOG
const (
	WDOG1_BASE uintptr = 0x400B8000 // WDOG
	WDOG2_BASE uintptr = 0x400D0000 // WDOG
)

// XBARA
const (
	XBARA1_BASE uintptr = 0x403BC000 // Crossbar Switch
	XBARB2_BASE uintptr = 0x403C0000 // Crossbar Switch
	XBARB3_BASE uintptr = 0x403C4000 // Crossbar Switch
)

// XTALOSC24M
const (
	XTALOSC24M_BASE uintptr = 0x400D8000 // XTALOSC24M
)
