// DO NOT EDIT THIS FILE. GENERATED BY svdxgen.

//go:build imxrt1060

// Package gpio provides access to the registers of the GPIO peripheral.
//
// Instances:
//  GPIO1  GPIO1_BASE  -  GPIO1_INT0*,GPIO1_INT1*,GPIO1_INT2*,GPIO1_INT3*,GPIO1_INT4*,GPIO1_INT5*,GPIO1_INT6*,GPIO1_INT7*,GPIO1_Combined_0_15*,GPIO1_Combined_16_31*
//  GPIO2  GPIO2_BASE  -  GPIO2_Combined_0_15*,GPIO2_Combined_16_31*
//  GPIO3  GPIO3_BASE  -  GPIO3_Combined_0_15*,GPIO3_Combined_16_31*
//  GPIO4  GPIO4_BASE  -  GPIO4_Combined_0_15*,GPIO4_Combined_16_31*
//  GPIO5  GPIO5_BASE  -  GPIO5_Combined_0_15*,GPIO5_Combined_16_31*
//  GPIO6  GPIO6_BASE  -  GPIO6_7_8_9*
//  GPIO7  GPIO7_BASE  -  GPIO6_7_8_9*
//  GPIO8  GPIO8_BASE  -  GPIO6_7_8_9*
//  GPIO9  GPIO9_BASE  -  GPIO6_7_8_9*
// Registers:
//  0x000 32  DR         GPIO data register
//  0x004 32  GDIR       GPIO direction register
//  0x008 32  PSR        GPIO pad status register
//  0x00C 32  ICR1       GPIO interrupt configuration register1
//  0x010 32  ICR2       GPIO interrupt configuration register2
//  0x014 32  IMR        GPIO interrupt mask register
//  0x018 32  ISR        GPIO interrupt status register
//  0x01C 32  EDGE_SEL   GPIO edge select register
//  0x084 32  DR_SET     GPIO data register SET
//  0x088 32  DR_CLEAR   GPIO data register CLEAR
//  0x08C 32  DR_TOGGLE  GPIO data register TOGGLE
// Import:
//  github.com/embeddedgo/imxrt/p/mmap
package gpio

const (
	IC0          ICR1 = 0x03 << 0  //+ Configuration for GPIO interrupt 0
	IC0_LOW      ICR1 = 0x00 << 0  //  Interrupt 0 is low-level sensitive.
	IC0_HIGH     ICR1 = 0x01 << 0  //  Interrupt 0 is high-level sensitive.
	IC0_RISING   ICR1 = 0x02 << 0  //  Interrupt 0 is rising-edge sensitive.
	IC0_FALLING  ICR1 = 0x03 << 0  //  Interrupt 0 is falling-edge sensitive.
	IC1          ICR1 = 0x03 << 2  //+ Configuration for GPIO interrupt 1
	IC1_LOW      ICR1 = 0x00 << 2  //  Interrupt 1 is low-level sensitive.
	IC1_HIGH     ICR1 = 0x01 << 2  //  Interrupt 1 is high-level sensitive.
	IC1_RISING   ICR1 = 0x02 << 2  //  Interrupt 1 is rising-edge sensitive.
	IC1_FALLING  ICR1 = 0x03 << 2  //  Interrupt 1 is falling-edge sensitive.
	IC2          ICR1 = 0x03 << 4  //+ Configuration for GPIO interrupt 2
	IC2_LOW      ICR1 = 0x00 << 4  //  Interrupt 2 is low-level sensitive.
	IC2_HIGH     ICR1 = 0x01 << 4  //  Interrupt 2 is high-level sensitive.
	IC2_RISING   ICR1 = 0x02 << 4  //  Interrupt 2 is rising-edge sensitive.
	IC2_FALLING  ICR1 = 0x03 << 4  //  Interrupt 2 is falling-edge sensitive.
	IC3          ICR1 = 0x03 << 6  //+ Configuration for GPIO interrupt 3
	IC3_LOW      ICR1 = 0x00 << 6  //  Interrupt 3 is low-level sensitive.
	IC3_HIGH     ICR1 = 0x01 << 6  //  Interrupt 3 is high-level sensitive.
	IC3_RISING   ICR1 = 0x02 << 6  //  Interrupt 3 is rising-edge sensitive.
	IC3_FALLING  ICR1 = 0x03 << 6  //  Interrupt 3 is falling-edge sensitive.
	IC4          ICR1 = 0x03 << 8  //+ Configuration for GPIO interrupt 4
	IC4_LOW      ICR1 = 0x00 << 8  //  Interrupt 4 is low-level sensitive.
	IC4_HIGH     ICR1 = 0x01 << 8  //  Interrupt 4 is high-level sensitive.
	IC4_RISING   ICR1 = 0x02 << 8  //  Interrupt 4 is rising-edge sensitive.
	IC4_FALLING  ICR1 = 0x03 << 8  //  Interrupt 4 is falling-edge sensitive.
	IC5          ICR1 = 0x03 << 10 //+ Configuration for GPIO interrupt 5
	IC5_LOW      ICR1 = 0x00 << 10 //  Interrupt 5 is low-level sensitive.
	IC5_HIGH     ICR1 = 0x01 << 10 //  Interrupt 5 is high-level sensitive.
	IC5_RISING   ICR1 = 0x02 << 10 //  Interrupt 5 is rising-edge sensitive.
	IC5_FALLING  ICR1 = 0x03 << 10 //  Interrupt 5 is falling-edge sensitive.
	IC6          ICR1 = 0x03 << 12 //+ Configuration for GPIO interrupt 6
	IC6_LOW      ICR1 = 0x00 << 12 //  Interrupt 6 is low-level sensitive.
	IC6_HIGH     ICR1 = 0x01 << 12 //  Interrupt 6 is high-level sensitive.
	IC6_RISING   ICR1 = 0x02 << 12 //  Interrupt 6 is rising-edge sensitive.
	IC6_FALLING  ICR1 = 0x03 << 12 //  Interrupt 6 is falling-edge sensitive.
	IC7          ICR1 = 0x03 << 14 //+ Configuration for GPIO interrupt 7
	IC7_LOW      ICR1 = 0x00 << 14 //  Interrupt 7 is low-level sensitive.
	IC7_HIGH     ICR1 = 0x01 << 14 //  Interrupt 7 is high-level sensitive.
	IC7_RISING   ICR1 = 0x02 << 14 //  Interrupt 7 is rising-edge sensitive.
	IC7_FALLING  ICR1 = 0x03 << 14 //  Interrupt 7 is falling-edge sensitive.
	IC8          ICR1 = 0x03 << 16 //+ Configuration for GPIO interrupt 8
	IC8_LOW      ICR1 = 0x00 << 16 //  Interrupt 8 is low-level sensitive.
	IC8_HIGH     ICR1 = 0x01 << 16 //  Interrupt 8 is high-level sensitive.
	IC8_RISING   ICR1 = 0x02 << 16 //  Interrupt 8 is rising-edge sensitive.
	IC8_FALLING  ICR1 = 0x03 << 16 //  Interrupt 8 is falling-edge sensitive.
	IC9          ICR1 = 0x03 << 18 //+ Configuration for GPIO interrupt 9
	IC9_LOW      ICR1 = 0x00 << 18 //  Interrupt 9 is low-level sensitive.
	IC9_HIGH     ICR1 = 0x01 << 18 //  Interrupt 9 is high-level sensitive.
	IC9_RISING   ICR1 = 0x02 << 18 //  Interrupt 9 is rising-edge sensitive.
	IC9_FALLING  ICR1 = 0x03 << 18 //  Interrupt 9 is falling-edge sensitive.
	IC10         ICR1 = 0x03 << 20 //+ Configuration for GPIO interrupt 10
	IC10_LOW     ICR1 = 0x00 << 20 //  Interrupt 10 is low-level sensitive.
	IC10_HIGH    ICR1 = 0x01 << 20 //  Interrupt 10 is high-level sensitive.
	IC10_RISING  ICR1 = 0x02 << 20 //  Interrupt 10 is rising-edge sensitive.
	IC10_FALLING ICR1 = 0x03 << 20 //  Interrupt 10 is falling-edge sensitive.
	IC11         ICR1 = 0x03 << 22 //+ Configuration for GPIO interrupt 11
	IC11_LOW     ICR1 = 0x00 << 22 //  Interrupt 11 is low-level sensitive.
	IC11_HIGH    ICR1 = 0x01 << 22 //  Interrupt 11 is high-level sensitive.
	IC11_RISING  ICR1 = 0x02 << 22 //  Interrupt 11 is rising-edge sensitive.
	IC11_FALLING ICR1 = 0x03 << 22 //  Interrupt 11 is falling-edge sensitive.
	IC12         ICR1 = 0x03 << 24 //+ Configuration for GPIO interrupt 12
	IC12_LOW     ICR1 = 0x00 << 24 //  Interrupt 12 is low-level sensitive.
	IC12_HIGH    ICR1 = 0x01 << 24 //  Interrupt 12 is high-level sensitive.
	IC12_RISING  ICR1 = 0x02 << 24 //  Interrupt 12 is rising-edge sensitive.
	IC12_FALLING ICR1 = 0x03 << 24 //  Interrupt 12 is falling-edge sensitive.
	IC13         ICR1 = 0x03 << 26 //+ Configuration for GPIO interrupt 13
	IC13_LOW     ICR1 = 0x00 << 26 //  Interrupt 13 is low-level sensitive.
	IC13_HIGH    ICR1 = 0x01 << 26 //  Interrupt 13 is high-level sensitive.
	IC13_RISING  ICR1 = 0x02 << 26 //  Interrupt 13 is rising-edge sensitive.
	IC13_FALLING ICR1 = 0x03 << 26 //  Interrupt 13 is falling-edge sensitive.
	IC14         ICR1 = 0x03 << 28 //+ Configuration for GPIO interrupt 14
	IC14_LOW     ICR1 = 0x00 << 28 //  Interrupt 14 is low-level sensitive.
	IC14_HIGH    ICR1 = 0x01 << 28 //  Interrupt 14 is high-level sensitive.
	IC14_RISING  ICR1 = 0x02 << 28 //  Interrupt 14 is rising-edge sensitive.
	IC14_FALLING ICR1 = 0x03 << 28 //  Interrupt 14 is falling-edge sensitive.
	IC15         ICR1 = 0x03 << 30 //+ Configuration for GPIO interrupt 15
	IC15_LOW     ICR1 = 0x00 << 30 //  Interrupt 15 is low-level sensitive.
	IC15_HIGH    ICR1 = 0x01 << 30 //  Interrupt 15 is high-level sensitive.
	IC15_RISING  ICR1 = 0x02 << 30 //  Interrupt 15 is rising-edge sensitive.
	IC15_FALLING ICR1 = 0x03 << 30 //  Interrupt 15 is falling-edge sensitive.
)

const (
	IC0n  = 0
	IC1n  = 2
	IC2n  = 4
	IC3n  = 6
	IC4n  = 8
	IC5n  = 10
	IC6n  = 12
	IC7n  = 14
	IC8n  = 16
	IC9n  = 18
	IC10n = 20
	IC11n = 22
	IC12n = 24
	IC13n = 26
	IC14n = 28
	IC15n = 30
)

const (
	IC16         ICR2 = 0x03 << 0  //+ Configuration for GPIO interrupt 16
	IC16_LOW     ICR2 = 0x00 << 0  //  Interrupt 16 is low-level sensitive.
	IC16_HIGH    ICR2 = 0x01 << 0  //  Interrupt 16 is high-level sensitive.
	IC16_RISING  ICR2 = 0x02 << 0  //  Interrupt 16 is rising-edge sensitive.
	IC16_FALLING ICR2 = 0x03 << 0  //  Interrupt 16 is falling-edge sensitive.
	IC17         ICR2 = 0x03 << 2  //+ Configuration for GPIO interrupt 17
	IC17_LOW     ICR2 = 0x00 << 2  //  Interrupt 17 is low-level sensitive.
	IC17_HIGH    ICR2 = 0x01 << 2  //  Interrupt 17 is high-level sensitive.
	IC17_RISING  ICR2 = 0x02 << 2  //  Interrupt 17 is rising-edge sensitive.
	IC17_FALLING ICR2 = 0x03 << 2  //  Interrupt 17 is falling-edge sensitive.
	IC18         ICR2 = 0x03 << 4  //+ Configuration for GPIO interrupt 18
	IC18_LOW     ICR2 = 0x00 << 4  //  Interrupt 18 is low-level sensitive.
	IC18_HIGH    ICR2 = 0x01 << 4  //  Interrupt 18 is high-level sensitive.
	IC18_RISING  ICR2 = 0x02 << 4  //  Interrupt 18 is rising-edge sensitive.
	IC18_FALLING ICR2 = 0x03 << 4  //  Interrupt 18 is falling-edge sensitive.
	IC19         ICR2 = 0x03 << 6  //+ Configuration for GPIO interrupt 19
	IC19_LOW     ICR2 = 0x00 << 6  //  Interrupt 19 is low-level sensitive.
	IC19_HIGH    ICR2 = 0x01 << 6  //  Interrupt 19 is high-level sensitive.
	IC19_RISING  ICR2 = 0x02 << 6  //  Interrupt 19 is rising-edge sensitive.
	IC19_FALLING ICR2 = 0x03 << 6  //  Interrupt 19 is falling-edge sensitive.
	IC20         ICR2 = 0x03 << 8  //+ Configuration for GPIO interrupt 20
	IC20_LOW     ICR2 = 0x00 << 8  //  Interrupt 20 is low-level sensitive.
	IC20_HIGH    ICR2 = 0x01 << 8  //  Interrupt 20 is high-level sensitive.
	IC20_RISING  ICR2 = 0x02 << 8  //  Interrupt 20 is rising-edge sensitive.
	IC20_FALLING ICR2 = 0x03 << 8  //  Interrupt 20 is falling-edge sensitive.
	IC21         ICR2 = 0x03 << 10 //+ Configuration for GPIO interrupt 21
	IC21_LOW     ICR2 = 0x00 << 10 //  Interrupt 21 is low-level sensitive.
	IC21_HIGH    ICR2 = 0x01 << 10 //  Interrupt 21 is high-level sensitive.
	IC21_RISING  ICR2 = 0x02 << 10 //  Interrupt 21 is rising-edge sensitive.
	IC21_FALLING ICR2 = 0x03 << 10 //  Interrupt 21 is falling-edge sensitive.
	IC22         ICR2 = 0x03 << 12 //+ Configuration for GPIO interrupt 22
	IC22_LOW     ICR2 = 0x00 << 12 //  Interrupt 22 is low-level sensitive.
	IC22_HIGH    ICR2 = 0x01 << 12 //  Interrupt 22 is high-level sensitive.
	IC22_RISING  ICR2 = 0x02 << 12 //  Interrupt 22 is rising-edge sensitive.
	IC22_FALLING ICR2 = 0x03 << 12 //  Interrupt 22 is falling-edge sensitive.
	IC23         ICR2 = 0x03 << 14 //+ Configuration for GPIO interrupt 23
	IC23_LOW     ICR2 = 0x00 << 14 //  Interrupt 23 is low-level sensitive.
	IC23_HIGH    ICR2 = 0x01 << 14 //  Interrupt 23 is high-level sensitive.
	IC23_RISING  ICR2 = 0x02 << 14 //  Interrupt 23 is rising-edge sensitive.
	IC23_FALLING ICR2 = 0x03 << 14 //  Interrupt 23 is falling-edge sensitive.
	IC24         ICR2 = 0x03 << 16 //+ Configuration for GPIO interrupt 24
	IC24_LOW     ICR2 = 0x00 << 16 //  Interrupt 24 is low-level sensitive.
	IC24_HIGH    ICR2 = 0x01 << 16 //  Interrupt 24 is high-level sensitive.
	IC24_RISING  ICR2 = 0x02 << 16 //  Interrupt 24 is rising-edge sensitive.
	IC24_FALLING ICR2 = 0x03 << 16 //  Interrupt 24 is falling-edge sensitive.
	IC25         ICR2 = 0x03 << 18 //+ Configuration for GPIO interrupt 25
	IC25_LOW     ICR2 = 0x00 << 18 //  Interrupt 25 is low-level sensitive.
	IC25_HIGH    ICR2 = 0x01 << 18 //  Interrupt 25 is high-level sensitive.
	IC25_RISING  ICR2 = 0x02 << 18 //  Interrupt 25 is rising-edge sensitive.
	IC25_FALLING ICR2 = 0x03 << 18 //  Interrupt 25 is falling-edge sensitive.
	IC26         ICR2 = 0x03 << 20 //+ Configuration for GPIO interrupt 26
	IC26_LOW     ICR2 = 0x00 << 20 //  Interrupt 26 is low-level sensitive.
	IC26_HIGH    ICR2 = 0x01 << 20 //  Interrupt 26 is high-level sensitive.
	IC26_RISING  ICR2 = 0x02 << 20 //  Interrupt 26 is rising-edge sensitive.
	IC26_FALLING ICR2 = 0x03 << 20 //  Interrupt 26 is falling-edge sensitive.
	IC27         ICR2 = 0x03 << 22 //+ Configuration for GPIO interrupt 27
	IC27_LOW     ICR2 = 0x00 << 22 //  Interrupt 27 is low-level sensitive.
	IC27_HIGH    ICR2 = 0x01 << 22 //  Interrupt 27 is high-level sensitive.
	IC27_RISING  ICR2 = 0x02 << 22 //  Interrupt 27 is rising-edge sensitive.
	IC27_FALLING ICR2 = 0x03 << 22 //  Interrupt 27 is falling-edge sensitive.
	IC28         ICR2 = 0x03 << 24 //+ Configuration for GPIO interrupt 28
	IC28_LOW     ICR2 = 0x00 << 24 //  Interrupt 28 is low-level sensitive.
	IC28_HIGH    ICR2 = 0x01 << 24 //  Interrupt 28 is high-level sensitive.
	IC28_RISING  ICR2 = 0x02 << 24 //  Interrupt 28 is rising-edge sensitive.
	IC28_FALLING ICR2 = 0x03 << 24 //  Interrupt 28 is falling-edge sensitive.
	IC29         ICR2 = 0x03 << 26 //+ Configuration for GPIO interrupt 29
	IC29_LOW     ICR2 = 0x00 << 26 //  Interrupt 29 is low-level sensitive.
	IC29_HIGH    ICR2 = 0x01 << 26 //  Interrupt 29 is high-level sensitive.
	IC29_RISING  ICR2 = 0x02 << 26 //  Interrupt 29 is rising-edge sensitive.
	IC29_FALLING ICR2 = 0x03 << 26 //  Interrupt 29 is falling-edge sensitive.
	IC30         ICR2 = 0x03 << 28 //+ Configuration for GPIO interrupt 30
	IC30_LOW     ICR2 = 0x00 << 28 //  Interrupt 30 is low-level sensitive.
	IC30_HIGH    ICR2 = 0x01 << 28 //  Interrupt 30 is high-level sensitive.
	IC30_RISING  ICR2 = 0x02 << 28 //  Interrupt 30 is rising-edge sensitive.
	IC30_FALLING ICR2 = 0x03 << 28 //  Interrupt 30 is falling-edge sensitive.
	IC31         ICR2 = 0x03 << 30 //+ Configuration for GPIO interrupt 31
	IC31_LOW     ICR2 = 0x00 << 30 //  Interrupt 31 is low-level sensitive.
	IC31_HIGH    ICR2 = 0x01 << 30 //  Interrupt 31 is high-level sensitive.
	IC31_RISING  ICR2 = 0x02 << 30 //  Interrupt 31 is rising-edge sensitive.
	IC31_FALLING ICR2 = 0x03 << 30 //  Interrupt 31 is falling-edge sensitive.
)

const (
	IC16n = 0
	IC17n = 2
	IC18n = 4
	IC19n = 6
	IC20n = 8
	IC21n = 10
	IC22n = 12
	IC23n = 14
	IC24n = 16
	IC25n = 18
	IC26n = 20
	IC27n = 22
	IC28n = 24
	IC29n = 26
	IC30n = 28
	IC31n = 30
)
